### ISSUE TITLE
CI/CD Setup & Test Automation Todo List

### ISSUE THREAD

**Issue by in-ch** [in-ch/utils#1]
- [ ] Set up GitHub Actions Workflow
- [ ] Set up Deployment Automation
- [ ] Configure GitHub Secrets
- [ ] Install and Configure Husky
- [ ] Set up Commitlint
- [ ] Set up ESLint
- [ ] Set up Prettier
- [ ] Automate Changelog Generation
- [ ] Check Test Coverage
